### ISSUE TITLE
Add a ChangeLog for crate users

### ISSUE THREAD

**Issue by linkmauve** [aws/dcv-color-primitives#51]
Hi, and congrats for your 0.2.0 release!

As the 0.1 branch is still used in the [image crate](https://www.image-rs.org/projects/image.html), it would be super useful for us to know what were the improvements, changes, and even more importantly breaking changes between 0.1 and 0.2.

Thanks. :)

**Comment by pbor** [comment]
Hi!

An high level changelog can be found here: https://github.com/aws/dcv-color-primitives/blob/master/NEWS

0.2 is backward compatible with 0.1 and we definitely suggest all users to update since we do not see any drawbacks.

The reason why we decided to bump to 0.2 is because there are some API additions and also because the improvements felt larger than the ones between other 0.1.x releases.


Feel free to reopen if you have more questions!
