### ISSUE TITLE
Direct nv12 to rgb?

### ISSUE THREAD

**Issue by seddonm1** [aws/dcv-color-primitives#70]
Hi,
Is there anything significant preventing a direct nv12 to rgb conversion? Currently we are doing nv12 to bgra to rgb.
Thanks

**Comment by fabiosky** [comment]
Hi Mike,

there is no significant issue, we have not added it because we are not currently using such conversion, however we would definitely take a patch to add it.

Add the support needs implementing some boilerplate code and performing the output conversion from aos to soa as final step of the conversion kernel.
